[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm run preview"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[phases.setup]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmd = "npm run preview"

[env]
NODE_ENV = "production"
PORT = "3000"